worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  charset utf-8; 

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;

  gzip on;
  gzip_disable "msie6";
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml application/font-woff2;

  server {
    listen 8080 http2;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|jpg|jpeg|png|gif|ico|svg)$ {
      etag on;
      add_header Cache-Control "public, no-cache, must-revalidate";
    }

    location ~* \.(mp4|webm|ogg)$ {
        gzip off;
        sendfile off; 
        add_header X-Accel-Buffering "no" always; 
        etag on;
        add_header Cache-Control "public, no-cache, must-revalidate";
        add_header Accept-Ranges bytes;
    }

    location = /index.html {
      expires -1;
      add_header Cache-Control "no-cache, no-store, must-revalidate" always;
      try_files $uri =404;
    }
  }
}
